
spring:
  security:
    user:
      name: user
      password: password
    oauth2:
      client:
        registration:
          splitwise:
            client-id: ${SPLITWISE_CLIENT_ID}
            client-secret: ${SPLITWISE_CLIENT_SECRET}
            client-authentication-method: post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/authorize/oauth2/code/{registrationId}"
          #          okta:
          #            clientId: 1KKf9f4c4l4-OBUsn3iSKSyI
          #            clientSecret: lEtw5ptdsrzNVoV0jgeCI_9kU1UFr2l2I8orla7dc2p4dEUw
          notion:
            client-id: ${NOTION_CLIENT_ID}
            client-secret: ${NOTION_CLIENT_SECRET}
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/authorize/oauth2/code/{registrationId}"
        provider:
          splitwise:
            authorization-uri: https://secure.splitwise.com/oauth/authorize
            token-uri: https://secure.splitwise.com/oauth/token
          #            user-info-uri: https://your-subdomain.oktapreview.com/oauth2/v1/userinfo
          #            user-name-attribute: sub
          #            jwk-set-uri: https://your-subdomain.oktapreview.com/oauth2/v1/keys
          #          okta:
          notion:
            authorization-uri: https://api.notion.com/v1/oauth/authorize?owner=user
            token-uri: https://api.notion.com/v1/oauth/token
logging:
  level:
    root: debug
    reactor:
      netty:
        http:
          client: trace